# Generated by Django 5.1.7 on 2025-03-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250311_1003'),
        ('app', '0005_add_messagerie'),
    ]

    operations = [
    ]
