# Generated by Django 5.1.7 on 2025-03-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_petitions'),
        ('app', '0006_merge_0003_auto_20250311_1003_0005_add_messagerie'),
    ]

    operations = [
    ]
