# Generated by Django 5.1.7 on 2025-03-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_all_petitions_2'),
        ('app', '0007_merge_20250312_2040'),
    ]

    operations = [
    ]
