# Generated by Django 5.1.7 on 2025-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_0007_all_petitions_2_0007_merge_20250312_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerie',
            name='haine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='messagerie',
            name='insulte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='messagerie',
            name='menace',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='messagerie',
            name='toxicite',
            field=models.FloatField(default=0.0),
        ),
    ]
