# Generated by Django 5.1.7 on 2025-03-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_0007_all_petitions_2_0007_merge_20250312_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image_url',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
